# Generated by Django 2.1.3 on 2018-12-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('click_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForthLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('related_concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_links', to='knowledge.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('color', models.CharField(max_length=10, null=True)),
                ('t_is_f', models.CharField(max_length=30, null=True)),
                ('f_is_t', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('related_concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_links', to='knowledge.Concept')),
                ('relation_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.Relation')),
            ],
        ),
        migrations.AddField(
            model_name='forthlink',
            name='relation_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.Relation'),
        ),
        migrations.AddField(
            model_name='forthlink',
            name='to_link_partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_link_partner', to='knowledge.ToLink'),
        ),
    ]
