# Generated by Django 2.1.3 on 2018-12-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='create_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='modify_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='summary',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='_title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
