# Generated by Django 2.1.3 on 2018-11-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forthrelationentry',
            name='to_partner_relation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_partner_relation', to='knowledge.ToRelationEntry'),
        ),
        migrations.AlterField(
            model_name='torelationentry',
            name='related_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_relation', to='knowledge.Concept'),
        ),
    ]
