# Generated by Django 2.1.3 on 2018-12-18 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0002_auto_20181218_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='editors',
            field=models.ManyToManyField(related_name='editable_concepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_concepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='viewers',
            field=models.ManyToManyField(related_name='viewable_concepts', to=settings.AUTH_USER_MODEL),
        ),
    ]
