# Generated by Django 2.1.3 on 2019-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20190103_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='_title',
            field=models.CharField(max_length=100),
        ),
    ]
