# Generated by Django 2.1.3 on 2018-12-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20181218_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forth_concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forth_link', to='knowledge.Concept')),
                ('to_concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_link', to='knowledge.Concept')),
            ],
        ),
    ]
