# Generated by Django 2.1.3 on 2018-12-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='knowledge.Relation'),
        ),
        migrations.AlterField(
            model_name='link',
            name='forth_concept',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_link', to='knowledge.Concept'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='to_concept',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_link', to='knowledge.Concept'),
        ),
    ]
