# Generated by Django 2.1.3 on 2018-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20181218_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='_title',
            field=models.CharField(max_length=30),
        ),
    ]
