# Generated by Django 2.1.3 on 2018-11-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20181120_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forthrelationentry',
            name='to_relation_partner',
            field=models.OneToOneField(null=True, on_delete=None, related_name='forth_relation_partner', to='knowledge.ToRelationEntry'),
        ),
    ]
