# Generated by Django 2.1.3 on 2018-12-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_auto_20181218_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='modify_time',
            field=models.DateTimeField(null=True),
        ),
    ]
