# Generated by Django 2.1.3 on 2018-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_auto_20181121_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forthlink',
            name='t_is_f',
        ),
        migrations.RemoveField(
            model_name='tolink',
            name='f_is_t',
        ),
        migrations.AddField(
            model_name='relation',
            name='f_is_t',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='t_is_f',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
