# Generated by Django 2.1.3 on 2018-12-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_auto_20181121_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forthlink',
            name='related_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_links', to='knowledge.Concept'),
        ),
        migrations.AlterField(
            model_name='tolink',
            name='related_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_links', to='knowledge.Concept'),
        ),
    ]
